# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "jkDOPLVaVmOm5IuxkV8PmQBAazl+dIKkQzYlc0NhoAH8NLpJQuJPLyQJA/slnagCpk87FotbJSACSVCp5MvvOxTXlOdz4sNKYf0EtUvpiSXXi5kVX2IZWDMaDbpvMXpovamUKU3ai5dNIZmi2THGXr9u9abFZiSZ03o9Dp/B/uo3/u/RCUnRjOlyVpufdys1/nT70o7IF3GY6VmjNjQjxGmD5A+zwpXthRpcUrXXoTV5zlg12hYbEZZrgdDpoOZiajbUsSEFX3SNITgHNjXHDLgozZGA0EojNka+mDZCkp6kJ6BkKbDizVLqLctBzfeNOR51qgnbooUHNx/OOmrVHt1AfQAwNK9eWMhbQIn+KUXXOAvXPnQHZs418qQoxbu4juJ+c1QYkCiIkUJ0mJcU4gulOaZ0tQ4WgmBTp5gaWZ5DRHGNPtYsK5s8dUUT+czpeHruMX7ciNz3SHuFudq7HoH6bBLP39lAnFCzP5ozyNwt6gqGeRp5fg8tWuIToV0gP0uKFkGldMk4GmVNaKiTzWs52w28y+zSC44q6XBbwgecOGWpOL+Wd4LYXEcl5Ik14gDfyXqCeRkHxb9pzu4dfr6ZMj/arIqjsU36NkGTq70+f+aCnbGNW8cNK1HpHPX7+3am9cktDZBrbMOcAvaT16eC0yYQEpcCH2DkzN7uzj4="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
