travis:
  secure:
    BINSTAR_TOKEN: jkDOPLVaVmOm5IuxkV8PmQBAazl+dIKkQzYlc0NhoAH8NLpJQuJPLyQJA/slnagCpk87FotbJSACSVCp5MvvOxTXlOdz4sNKYf0EtUvpiSXXi5kVX2IZWDMaDbpvMXpovamUKU3ai5dNIZmi2THGXr9u9abFZiSZ03o9Dp/B/uo3/u/RCUnRjOlyVpufdys1/nT70o7IF3GY6VmjNjQjxGmD5A+zwpXthRpcUrXXoTV5zlg12hYbEZZrgdDpoOZiajbUsSEFX3SNITgHNjXHDLgozZGA0EojNka+mDZCkp6kJ6BkKbDizVLqLctBzfeNOR51qgnbooUHNx/OOmrVHt1AfQAwNK9eWMhbQIn+KUXXOAvXPnQHZs418qQoxbu4juJ+c1QYkCiIkUJ0mJcU4gulOaZ0tQ4WgmBTp5gaWZ5DRHGNPtYsK5s8dUUT+czpeHruMX7ciNz3SHuFudq7HoH6bBLP39lAnFCzP5ozyNwt6gqGeRp5fg8tWuIToV0gP0uKFkGldMk4GmVNaKiTzWs52w28y+zSC44q6XBbwgecOGWpOL+Wd4LYXEcl5Ik14gDfyXqCeRkHxb9pzu4dfr6ZMj/arIqjsU36NkGTq70+f+aCnbGNW8cNK1HpHPX7+3am9cktDZBrbMOcAvaT16eC0yYQEpcCH2DkzN7uzj4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
